### PR TITLE
[Resolves #36] Fix Getting Started section to use class

### LINKED ISSUE #36: Ajaxinate page says to use ID but code uses Class
Had to look around in the source code since following the get started page: https://elkfox.github.io/Ajaxinate/ didn't work. 

The get started page says to use id="AjaxinateLoop" when in fact, the code uses class="AjaxinateLoop"

### PR DESCRIPTION
**Pull request by stanleynguyen**
Example in Getting Started section demonstrating the default example using ID instead of classes, which differs from the default in source code

### CODE REVIEW

**Comment by Cam** [comment]
@stanleynguyen Thanks for this. Looks good.

I had been intending to change the defaults to use an ID, rather than a class. That would mean changing the documentation in a different area instead.

What are your thoughts on that approach? I'm happy to forget that for now and merge this if using IDs for selectors doesn't have consensus. Let me know.

**Comment by stanleynguyen** [comment]
@Cam I actually think changing the default to ID would be better. I can change the implementation and documentation as well

**Comment by Cam** [comment]
@stanleynguyen Sounds good to me! If you would like to update your fork and resubmit the PR I'll get that merged ASAP 👍

**Comment by stanleynguyen** [comment]
I will rework the implementation and edit the documentation accordingly

**Comment by stanleynguyen** [comment]
Hey @Cam I'm struggling with the release process. May I get some help from you? `npm run release major` doesn't seem to work, giving "Task major is not in the gulpfile" error

**Comment by Cam** [comment]
Hi @stanleynguyen. For sure! I'll need to run the new release. If you create the new PR, I'll merge it then run it up.

**Pull request closed without merging**
